//! Renders a selected pack into portable, self-contained Markdown.
//!
//! The output is intentionally boring and deterministic: fixed section order,
//! stably-sorted tables, and code fences sized to survive files that themselves
//! contain backtick runs. The graph store is consulted only to list the symbols
//! declared in the included files.

use crate::config::SynapseConfig;
use crate::git::{self, GitInfo};
use crate::graph::GraphStore;
use crate::graph::model::SymbolSearchQuery;
use crate::indexer::languages;
use crate::pack::{PackMode, PackRequest, SelectedFile};
use crate::repo::Repo;
use anyhow::Result;
use std::fmt::Write as _;

/// Escape a value for safe inclusion in a Markdown table cell.
fn escape_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

/// Choose a code-fence string longer than any backtick run inside `content`,
/// so file bodies that contain ``` cannot prematurely close the block.
fn fence_for(content: &str) -> String {
    let mut longest = 0usize;
    let mut current = 0usize;
    for ch in content.chars() {
        if ch == '`' {
            current += 1;
            if current > longest {
                longest = current;
            }
        } else {
            current = 0;
        }
    }
    // At least three backticks; one more than the longest run present.
    "`".repeat(longest.max(2) + 1)
}

/// Render the selected files (and supporting metadata) as a Markdown context
/// pack. Deterministic across runs for identical inputs.
pub fn render(
    repo: &Repo,
    config: &SynapseConfig,
    store: &dyn GraphStore,
    git: &GitInfo,
    req: &PackRequest,
    sel: &[SelectedFile],
) -> Result<String> {
    let mut out = String::new();

    out.push_str("# SimCube Synapse Context Pack\n\n");
    out.push_str("Generated by `synapse`.\n\n");

    // ---- Request ----------------------------------------------------------
    out.push_str("## Request\n\n");
    let _ = writeln!(out, "- Mode: {}", req.mode.label());
    let _ = writeln!(out, "- Query: {}", req.mode.query_text());
    let _ = writeln!(out, "- Budget: {} tokens", req.budget);
    out.push('\n');

    // ---- Selection Summary ------------------------------------------------
    out.push_str("## Selection Summary\n\n");
    out.push_str("| File | Reason | Estimated Tokens |\n");
    out.push_str("|---|---|---:|\n");
    for f in sel {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            escape_cell(&f.path),
            escape_cell(&f.reason),
            f.estimated_tokens
        );
    }
    out.push('\n');

    // ---- Repository Metadata ---------------------------------------------
    out.push_str("## Repository Metadata\n\n");
    let repo_name = if config.repo.name.is_empty() {
        "(unnamed)"
    } else {
        config.repo.name.as_str()
    };
    let branch = git.branch.as_deref().unwrap_or("(unknown)");
    let commit = git.commit.as_deref().unwrap_or("(unknown)");
    let changed_included = if req.mode == PackMode::Changed {
        "yes"
    } else {
        "no"
    };
    let _ = writeln!(out, "- Repo: {repo_name}");
    let _ = writeln!(out, "- Branch: {branch}");
    let _ = writeln!(out, "- Commit: {commit}");
    let _ = writeln!(out, "- Changed files included: {changed_included}");
    out.push_str("- Graph backend: LadybugDB\n");
    out.push('\n');

    // ---- Symbols ----------------------------------------------------------
    out.push_str("## Symbols\n\n");
    let included_paths: Vec<&str> = sel
        .iter()
        .filter(|f| f.included)
        .map(|f| f.path.as_str())
        .collect();

    let mut symbols = Vec::new();
    for path in &included_paths {
        let query = SymbolSearchQuery {
            file: Some((*path).to_string()),
            ..Default::default()
        };
        symbols.extend(store.symbols_matching(&query)?);
    }
    // Deterministic order: by file path, then start line, then name/kind id.
    symbols.sort_by(|a, b| {
        a.file_path
            .cmp(&b.file_path)
            .then(a.start_line.cmp(&b.start_line))
            .then(a.name.cmp(&b.name))
            .then(a.id.cmp(&b.id))
    });

    if symbols.is_empty() {
        out.push_str("_No symbols extracted for the selected files._\n\n");
    } else {
        out.push_str("| Symbol | Kind | Language | File |\n");
        out.push_str("|---|---|---|---|\n");
        for s in &symbols {
            let _ = writeln!(
                out,
                "| {} | {} | {} | {} |",
                escape_cell(&s.name),
                s.kind,
                s.language,
                escape_cell(&s.file_path)
            );
        }
        out.push('\n');
    }

    // ---- Diff (optional) --------------------------------------------------
    if req.include_diff
        && let Some(diff_text) = git::diff(&repo.root)
    {
        out.push_str("## Diff\n\n");
        let fence = fence_for(&diff_text);
        let _ = writeln!(out, "{fence}diff");
        out.push_str(&diff_text);
        if !diff_text.ends_with('\n') {
            out.push('\n');
        }
        let _ = writeln!(out, "{fence}");
        out.push('\n');
    }

    // In dry-run mode we stop before emitting any file bodies.
    if req.dry_run {
        return Ok(out);
    }

    // ---- Files ------------------------------------------------------------
    out.push_str("## Files\n\n");
    for f in sel.iter().filter(|f| f.included) {
        let full = repo.root.join(&f.path);
        let contents = std::fs::read(&full)
            .map(|bytes| String::from_utf8_lossy(&bytes).into_owned())
            .unwrap_or_default();

        let _ = writeln!(out, "### {}\n", f.path);
        let _ = writeln!(out, "Reason: {}\n", f.reason);

        let lang = languages::detect(&f.path);
        let fence = fence_for(&contents);
        let _ = writeln!(out, "{}{}", fence, lang.fence());
        out.push_str(&contents);
        if !contents.ends_with('\n') {
            out.push('\n');
        }
        let _ = writeln!(out, "{fence}");
        out.push('\n');
    }

    Ok(out)
}
